default:
    folder: /data/disk/logs/checkpoints
    s3_bucket: chungwoolee
    # arn:aws:s3:::chungwoolee
    save_code: True
    keep_top: 5
default_local:
    folder: /data/disk/logs/checkpoints
    save_code: True
    keep_top: 5