default:
    seed: 42
    min_epochs: 0
    max_epochs: 50
    grad_scaler: False
    find_unused_parameters: False
    flip_lr_prob: 0.5
    validate_first: False
    validate_flipped: True
    sync_batch_norm: True
    grad_accumulate_batches: 0
