wrapper:
    recipe: wrapper|default
    max_epochs: 10
arch:
    model:
        file: depth/FSMModel
    networks:
        depth:
            recipe: networks/focal_depth_res_net|fsm_ddad
        pose:
            recipe: networks/conv_pose_net|default
    losses:
        reprojection:
            recipe: losses/reprojection|fsm
        smoothness:
            recipe: losses/smoothness|default
evaluation:
    depth:
        recipe: evaluation/depth|ddad_resize
optimizers:
    depth:
        recipe: optimizers|adam_20_05
        lr: 0.0002
        scheduler:
            name: StepLR
            step_size: 15
            gamma: 0.5
    pose:
        recipe: optimizers|adam_20_05
        lr: 0.0002
        scheduler:
            name: StepLR
            step_size: 15
            gamma: 0.5
datasets:
    train:
        recipe: datasets/ddad|train_selfsup_6cams
        labels: [depth, pose]
        repeat: [1]
    validation:
        recipe: datasets/ddad|validation_6cams
        labels: [depth, pose]
        repeat: [1]
wandb:
    recipe: wandb|default
    project: vidar_baselines
    tags: ['fsm']
checkpoint:
    recipe: checkpoint|default
# save:
#     recipe: save|depth_splitname
