wrapper:
    recipe: wrapper|default
    max_epochs: 10
arch:
    model:
        file: depth/FSMSupervisedModel
    networks:
        depth:
            recipe: networks/focal_depth_res_net|fsm_ddad
        pose:
            recipe: networks/conv_pose_net|default
    losses:
        supervised:
            recipe: losses/supervised_depth|huber
        smoothness:
            recipe: losses/smoothness|default
evaluation:
    depth:
        recipe: evaluation/depth|ddad_resize
optimizers:
    depth:
        recipe: optimizers|adam_20_05
        lr: 0.0002
        scheduler:
            name: StepLR
            step_size: 15
            gamma: 0.5
    pose:
        recipe: optimizers|adam_20_05
        lr: 0.0002
        scheduler:
            name: StepLR
            step_size: 15
            gamma: 0.5
datasets:
    train:
        recipe: datasets/ddad_tiny|train_sup_6cams_fsm
        labels: [depth, pose]
        repeat: [1]
        dataloader:
          batch_size: 5
          num_workers: 5
    validation:
        recipe: datasets/ddad_tiny|validation_sup_6cams_fsm
        labels: [depth, pose]
        repeat: [1]
        dataloader:
          batch_size: 5
          num_workers: 5
# wandb:
#     recipe: wandb|default
#     project: fsm_supervised
#     tags: ['fsm_sup']
# checkpoint:
#     recipe: checkpoint|default
# save:
#     recipe: save|depth_splitname
