panodepth_ddad:
    file: depth/MultiCamDepthNet
    min_depth: 1.0
    max_depth: 200.0

    encoders:
        camera_01:
            file: encoders/MobileNetEncoder
            version: lcnet_100
            pretrained: True
            in_shape: [384, 640]
        camera_05:
            file: encoders/MobileNetEncoder
            version: lcnet_100
            pretrained: True
            in_shape: [384, 640]
        camera_06:
            file: encoders/MobileNetEncoder
            version: lcnet_100
            pretrained: True
            in_shape: [384, 640]
        camera_07:
            file: encoders/MobileNetEncoder
            version: lcnet_100
            pretrained: True
            in_shape: [384, 640]
        camera_08:
            file: encoders/MobileNetEncoder
            version: lcnet_100
            pretrained: True
            in_shape: [384, 640]
        camera_09:
            file: encoders/MobileNetEncoder
            version: lcnet_100
            pretrained: True
            in_shape: [384, 640]

    decoder:
        file: decoders/PanoDepthDecoder
        fusion_type: MultiDepthSweepFusion
        out_shape: [256, 2048]
        use_skips: True
        activation: sigmoid
        num_ch_out: 1
        downsample: False

