wrapper:
    recipe: wrapper|default
    validate_first: True
    validate_flipped: True
arch:
    model:
        file: depth/SurroundDepthModel
        checkpoint: [
            pretrained/ddad_scale/encoder.pth,
            pretrained/ddad_scale/depth.pth,
        ]
        add_prefix: [
            [encoder., networks.depth.networks.encoder.],
            [decoder., networks.depth.networks.decoder.],
            [decoder_cross., networks.depth.networks.decoder.],
        ]
    networks:
        depth:
            recipe: networks/surround_depth|sd_ddad
            # encoder:
            #     # file: encoders/ResNetEncoder
            #     version: 34
evaluation:
    depth:
        recipe: evaluation/depth|ddad_resize
        post_process: True
        only_first: True
        show_sensor_name: True

    # masked_depth:
    #     recipe: evaluation/depth|ddad_resize
    #     post_process: False
    #     distance_ranges:
    #         start: 1
    #         end: 200
    #         delta: 25
    #     angular_ranges:
    #         start: 0
    #         end: 360
    #         delta: 30

datasets:
    validation:
        recipe: datasets/ddad|validation_6cams
        # dataloader:
        #     num_workers: 0
        # recipe: datasets/ddad_tiny|validation_6cams
#         path: [
#             /data/datasets/DDAD/ddad_train_val/ddad_000186.json,
#             # /data/datasets/DDAD/ddad_train_val/ddad_000179.json,
#             # /data/datasets/DDAD/ddad_train_val/ddad_000171.json,
#             # /data/datasets/DDAD/ddad_train_val/ddad_000169.json,
#             # /data/datasets/DDAD/ddad_train_val/ddad_000168.json,
#             # /data/datasets/DDAD/ddad_train_val/ddad_000167.json,
#             # /data/datasets/DDAD/ddad_train_val/ddad_000160.json,
#             # /data/datasets/DDAD/ddad_train_val/ddad_000158.json,
#             # /data/datasets/DDAD/ddad_train_val/ddad_000157.json,
#             # /data/datasets/DDAD/ddad_train_val/ddad_000155.json,
#             # /data/datasets/DDAD/ddad_train_val/ddad_000153.json,
#         ]
# save:
#     recipe: save|depth_splitname
#     rgb: [gt, tgt]
#     depth: [gt_viz, gt_npz, viz, npz]
#     naming: filename