wrapper:
    recipe: wrapper|default
    validate_first: True
    validate_flipped: False
arch:
    model:
        file: depth/SurroundDepthModel
        checkpoint: [
            pretrained/ddad_scale/encoder.pth,
            pretrained/ddad_scale/depth.pth,
        ]
        add_prefix: [
            [encoder., networks.depth.networks.encoder.],
            [decoder., networks.depth.networks.decoder.],
            [decoder_cross., networks.depth.networks.decoder.],
        ]
    networks:
        depth:
            recipe: networks/surround_depth|sd_ddad
evaluation:
    depth:
        recipe: evaluation/depth|ddad_resize
        post_process: False
datasets:
    validation:
        recipe: datasets/ddad|validation_6cams
        # recipe: datasets/ddad_tiny|validation_6cams
#         path: [
#             /data/datasets/DDAD/ddad_train_val/ddad_000186.json,
#             # /data/datasets/DDAD/ddad_train_val/ddad_000179.json,
#             # /data/datasets/DDAD/ddad_train_val/ddad_000171.json,
#             # /data/datasets/DDAD/ddad_train_val/ddad_000169.json,
#             # /data/datasets/DDAD/ddad_train_val/ddad_000168.json,
#             # /data/datasets/DDAD/ddad_train_val/ddad_000167.json,
#             # /data/datasets/DDAD/ddad_train_val/ddad_000160.json,
#             # /data/datasets/DDAD/ddad_train_val/ddad_000158.json,
#             # /data/datasets/DDAD/ddad_train_val/ddad_000157.json,
#             # /data/datasets/DDAD/ddad_train_val/ddad_000155.json,
#             # /data/datasets/DDAD/ddad_train_val/ddad_000153.json,
#         ]
# save:
#     recipe: save|depth_splitname
#     rgb: [gt, tgt]
#     depth: [gt_viz, gt_npz, viz, npz]
#     naming: filename