wrapper:
    recipe: wrapper|default
    flip_lr_prob: 0.0
    validate_flipped: False
    validate_first: True
arch:
    model:
        file: depth/PanoCamSelfSupGTPoseModel
        checkpoint: pretrained/dulcet-plasma-9_epoch_009.ckpt
        checkpoint_strict: True
    networks:
        depth:
            recipe: networks/multicam_depth_net|panodepth_ddad_resnet
evaluation:
    panodepth:
        recipe: evaluation/depth|ddad_resize
        post_process: False
datasets:
    validation:
        # recipe: datasets/ddad|validation_panodepth
        recipe: datasets/ddad_tiny|validation_panodepth
        path: [
            /data/datasets/DDAD/ddad_train_val/ddad_000186.json,
            # /data/datasets/DDAD/ddad_train_val/ddad_000179.json,
            # /data/datasets/DDAD/ddad_train_val/ddad_000171.json,
            # /data/datasets/DDAD/ddad_train_val/ddad_000169.json,
            # /data/datasets/DDAD/ddad_train_val/ddad_000168.json,
            # /data/datasets/DDAD/ddad_train_val/ddad_000167.json,
            # /data/datasets/DDAD/ddad_train_val/ddad_000160.json,
            # /data/datasets/DDAD/ddad_train_val/ddad_000158.json,
            # /data/datasets/DDAD/ddad_train_val/ddad_000157.json,
            # /data/datasets/DDAD/ddad_train_val/ddad_000155.json,
            # /data/datasets/DDAD/ddad_train_val/ddad_000153.json,
        ]
        labels: [depth, pose]
        # dataloader:
        #   batch_size: 1
        #   num_workers: 0
save:
    recipe: save|depth_splitname
    type: PanoSaver
    rgb: [tgt]
    depth: [gt_viz, gt_npz, viz, npz]
    naming: filename
    store_data: False