wrapper:
    recipe: wrapper|default
    flip_lr_prob: 0.0
    # validate_first: True
    validate_flipped: False
arch:
    model:
        file: depth/PanoCamSelfSupGTPoseModel
    networks:
        depth:
            recipe: networks/multicam_depth_net|panodepth_ddad
            min_depth: 2.0
            max_depth: 200.0
        pose:
            recipe: networks/conv_pose_net|default
    losses:
        reprojection:
            recipe: losses/reprojection|panodepth
            automask_loss: False
        smoothness:
            recipe: losses/smoothness|default
evaluation:
    panodepth:
        recipe: evaluation/depth|ddad_resize
        post_process: False
optimizers:
    depth:
        recipe: optimizers|adam_20_05
    pose:
        recipe: optimizers|adam_20_05
datasets:
    train:
        recipe: datasets/ddad|train_selfsup_panodepth
        labels: [depth, pose]
        # augmentation:
        #   jittering: [0.4, 0.4, 0.4, 0.05]
        repeat: [1]
        dataloader:
          # (DDP) The batch size should be larger than the number of GPUs used locally.
          batch_size: 1
          num_workers: 20
    validation:
        recipe: datasets/ddad|validation_panodepth
        labels: [depth, pose]
        dataloader:
          batch_size: 1
          num_workers: 20
wandb:
    recipe: wandb|default
    project: vidar_panodepth_dev
    tags: ['panodepth', '220624']
    num_validation_logs: 10
checkpoint:
    recipe: checkpoint|default_local
