wrapper:
    recipe: wrapper|default
    flip_lr_prob: 0.0
    validate_flipped: False
arch:
    model:
        file: depth/PanoCamSelfSupGTPoseModel
    networks:
        depth:
            recipe: networks/multicam_depth_net|panodepth_ddad
            min_depth: 2.0
            max_depth: 200.0
            decoder:
              downsample: True
    losses:
        reprojection:
            recipe: losses/reprojection|panodepth_mono_stereo
            automask_loss: True
            flow_downsampling: True
        smoothness:
            recipe: losses/smoothness|default
evaluation:
    panodepth:
        recipe: evaluation/depth|ddad_resize
        post_process: False
optimizers:
    depth:
        recipe: optimizers|adam_20_05
        lr: 0.00005
datasets:
    train:
        recipe: datasets/ddad|train_selfsup_panodepth
        labels: [depth, pose]
        augmentation:
          # resize: [768, 1280]
          # resize: [576, 960]
          resize: [384, 640]
        repeat: [1]
        dataloader:
          batch_size: 1
          num_workers: 16   # If pin_memory is True, requires ~59GB RAM per 8 workers
    validation:
        recipe: datasets/ddad|validation_panodepth
        labels: [depth, pose]
        augmentation:
          # resize: [768, 1280]
          # resize: [576, 960]
          resize: [384, 640]
        dataloader:
          # pin_memory: False
          batch_size: 1
          num_workers: 16
wandb:
    recipe: wandb|default
    project: vidar_panodepth_monet
    tags: ['220631', 'loss_on_image', 'loss_on_pano', 'reproj_mono_stereo', 'flow_reversal_16pts']
    num_validation_logs: 10
checkpoint:
    recipe: checkpoint|default_local
