default:
    name: default
    position_in_world: [0, 0, 1.5]
    height: 256
    width: 2048
    rho: 1.0
    phi_range: [0, 6.2831853072]    # 6.2831853072 = 2 * pi
    z_range: [-0.3, 0.2]

standard:
    name: standard
    position_in_world: [0, 0, 1.5]
    height: 256
    width: 2048
    rho: 1.0
    phi_range: [0, 6.2831853072]    # 6.2831853072 = 2 * pi
    z_range: [-0.2, 0.2]
