wrapper:
    recipe: wrapper|default
    flip_lr_prob: 0.0
    validate_flipped: False
    validate_first: True
arch:
    model:
        file: depth/PanoSupervisedModel
        checkpoint: /data/disk/logs/checkpoints/soft-tree-60/models/020.ckpt
        checkpoint_strict: True
    networks:
        depth:
            recipe: networks/multicam_depth_net|panodepth_ddad_resnet
evaluation:
    panodepth:
        recipe: evaluation/depth|ddad_resize
        post_process: False
datasets:
    validation:
        # recipe: datasets/ddad|validation_panodepth
        recipe: datasets/ddad_tiny|validation_panodepth
        labels: [depth, pose]
        # dataloader:
        #   batch_size: 1
        #   num_workers: 0
save:
    recipe: save|depth_splitname
    type: PanoSaver
    rgb: [tgt]
    depth: [gt_viz, gt_npz, viz, npz]
    naming: filename
    store_data: False
