wrapper:
    recipe: wrapper|default
    flip_lr_prob: 0.0
    validate_flipped: False
    validate_first: True
arch:
    model:
        file: depth/PanoSupervisedModel
        checkpoint: /data1/disk/logs/checkpoints/driven-haze-175/models/011.ckpt
        checkpoint_strict: False
    networks:
        depth:
            recipe: networks/multicam_depth_net|panodepth_ddad_resnet
            min_depth: 2.0
            max_depth: 200.0
            scale_invdepth: inverse
            # Note: downsampled panodepth can reduce computation and memory,
            # but it makes the image depth blurry when filling the holes by interpolation.
            decoder:
              out_shape: [256, 2048]
              depth_hypothesis: [2, 3, 10, 30, 60, 90]
              view_attention: False
              # # Control output scale further, since intrinsics are calculated from panocam definition (256 x 2048)
              # [IMPORTANT] DO NOT TURN THIS ON. We'll lose the sharpness of the depth map we get.
              downsample: False
              positional_encoding: 16
              neighbor_map: {
                    'camera_01': ['camera_05', 'camera_06'],
                    'camera_05': ['camera_01', 'camera_07'],
                    'camera_06': ['camera_01', 'camera_08'],
                    'camera_07': ['camera_05', 'camera_09'],
                    'camera_08': ['camera_06', 'camera_09'],
                    'camera_09': ['camera_07', 'camera_08']
              }
              out_shape: [256, 2048]

evaluation:
    panodepth:
        recipe: evaluation/depth|ddad_resize
        post_process: False
        only_first: True
        show_sensor_name: True
datasets:
    validation:
        # recipe: datasets/ddad|validation_panodepth
        recipe: datasets/ddad_tiny_overfit|validation_panodepth
        labels: [depth, pose]
        dataloader:
            batch_size: 1
            num_workers: 4
            pin_memory: True
# wandb:
#     recipe: wandb|default
#     project: panodepth_res_net_tiny
#     tags: ['batch_4', 'train_on_filtered_DDAD', 'depth_hypothesis', 'positional_encoding_16', 'resnet_encoders']
#     num_validation_logs: 10
# save:
#     recipe: save|depth_splitname
