wrapper:
    recipe: wrapper|default
arch:
    model:
        file: depth/SelfSupervisedModel
    networks:
        depth:
            recipe: networks/mono_depth_res_net|default
            depth_range: [1.0,200.0]
        pose:
            recipe: networks/pose_net|default
    losses:
        reprojection:
            recipe: losses/reprojection|default
        smoothness:
            recipe: losses/smoothness|default
evaluation:
    depth:
        recipe: evaluation/depth|ddad_resize
optimizers:
    depth:
        recipe: optimizers|adam_20_05
    pose:
        recipe: optimizers|adam_20_05
datasets:
    train:
        recipe: datasets/ddad_tiny|train_selfsup_front
        labels: [depth, pose]
        repeat: [5]
    validation:
        recipe: datasets/ddad_tiny|validation_front
        labels: [depth, pose]
        context: [-1,1]
wandb:
    recipe: wandb|default
